version: "3.9"

services:
  mongo:
    container_name: mongo
    hostname: mongo.local
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_data_container:
    external: false
    labels:
      author: "Brian Vo"
      description: "mongo database"
