version: "3.9"

x-mongo-common: &mongo-common
  image: mongo:7.0.5
  volumes:
    - ./scripts:/scripts
  restart: on-failure
  networks:
    - mongo-minimize-network

services:

## Router
  ## Router
  router-1:
    <<: *mongo-common
    container_name: router-1
    command: mongos --port 27017 --configdb rs-config-server/configsvr-1:27017 --bind_ip_all
    ports:
      - 27117:27017

## Config Servers
  configsvr-1:
    <<: *mongo-common
    container_name: mongo-config-1 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    ports:
      - 27119:27017
    depends_on:
      - shard-1a
      - shard-2a 

## Shards
  ## Shards 01
  shard-1a:
    <<: *mongo-common
    container_name: shard-1-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-1
    ports:
      - 27122:27017
    depends_on:
      - shard-1b
      - shard-1c

  shard-1b:
    <<: *mongo-common
    container_name: shard-1-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-1
    ports:
      - 27123:27017

  shard-1c:
    <<: *mongo-common
    container_name: shard-1-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-1
    ports:
      - 27124:27017

  ## Shards 02
  shard-2a:
    <<: *mongo-common
    container_name: shard-2-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-2
    ports:
      - 27125:27017
    depends_on:
      - shard-2b
      - shard-2c

  shard-2b:
    <<: *mongo-common
    container_name: shard-2-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-2
    ports:
      - 27126:27017

  shard-2c:
    <<: *mongo-common
    container_name: shard-2-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-2
    ports:
      - 27127:27017

networks:
  mongo-minimize-network:
    driver: bridge